### ISSUE TITLE
Checklist de aplicativos a migrar

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/devops#7]
- [ ] [buda](http://api.datos.gob.mx)
- [ ] [adela](http://adela.datos.gob.mx)
- [ ] [ng-ckan](http://busca.datos.gob.mx)
- [ ] [datos.gob.mx](http://datos.gob.mx)
- [ ] [mxabierto.org](http://mxabierto.org)
- [ ] [Datatron](http://datatron.herokuapp.com)
- [ ] [Herramienta para la Agenda 2030](http://pnud.carto.mx)
- [ ] [Herramienta para cambio climatico](http://cambioclimatico.datos.gob.mx)
